global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus-monitor'

scrape_configs:
  - job_name: nginx
    static_configs:
      - targets: ['68.183.187.164:9113']
  - job_name: node-exporter
    static_configs:
      - targets: ['68.183.187.164:9100']
  - job_name: nginx-log-exporter
    static_configs:
      - targets: ['68.183.187.164:4040']
